server:
  port: 8001
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/customer?createDatabaseIfNotExist=true
