server:
  port: 8001
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/customer
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
